import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';

export async function POST(request: Request) {
    try {
        const { repository } = await request.json();

        const cookieStore = cookies();
        const token = cookieStore.get('github_token')?.value;

        if (!token) {
            return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
        }

        if (!repository) {
            return NextResponse.json({ error: 'Repository not specified' }, { status: 400 });
        }

        const [owner, repo] = repository.split('/');

        // Get the default branch
        const repoInfoResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
            headers: {
                Authorization: `Bearer ${token}`,
                Accept: 'application/vnd.github.v3+json',
            },
        });

        if (!repoInfoResponse.ok) {
            throw new Error('Failed to get repository info');
        }

        const repoInfo = await repoInfoResponse.json();
        const defaultBranch = repoInfo.default_branch;

        // Create a new branch
        const branchName = `metamorph-setup-${Date.now()}`;

        // Get the SHA of the default branch
        const refResponse = await fetch(
            `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${defaultBranch}`,
            {
                headers: {
                    Authorization: `Bearer ${token}`,
                    Accept: 'application/vnd.github.v3+json',
                },
            }
        );

        const refData = await refResponse.json();
        const sha = refData.object.sha;

        // Create new branch
        await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${token}`,
                Accept: 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                ref: `refs/heads/${branchName}`,
                sha,
            }),
        });

        // Read the workflow file template
        const workflowContent = `name: MetaMorph AI Self-Healing

on:
  repository_dispatch:
    types: [deploy-agent]

jobs:
  self-heal:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cline CLI
        run: |
          npm install -g @cline/cli

      - name: Run autonomous healing
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          cline --autonomous \\
            --task "\${{ github.event.client_payload.mission }}" \\
            --max-iterations 5

      - name: Run Oumi Evaluation
        run: |
          # Install Python dependencies
          pip install -r requirements.txt || echo "No requirements.txt"
          
          # Run evaluation if script exists
          if [ -f "scripts/oumi_eval.py" ]; then
            python scripts/oumi_eval.py src/ || echo "Evaluation complete"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix: Auto-heal code issues"
          title: "🤖 MetaMorph AI: Automated Code Fixes"
          body: |
            ## 🤖 Autonomous Code Healing
            
            This PR was automatically generated by MetaMorph AI.
            
            **Triggered by:** \${{ github.event.client_payload.triggered_by }}
            **Mission:** \${{ github.event.client_payload.mission }}
            
            ### Changes Made:
            - Analyzed code issues
            - Applied automated fixes
            - Evaluated code quality
            
            Please review the changes and merge if they look good!
          branch: metamorph-fixes
          delete-branch: true
`;

        // Create the workflow file
        const createFileResponse = await fetch(
            `https://api.github.com/repos/${owner}/${repo}/contents/.github/workflows/metamorph-ai.yml`,
            {
                method: 'PUT',
                headers: {
                    Authorization: `Bearer ${token}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    message: 'feat: Add MetaMorph AI self-healing workflow',
                    content: Buffer.from(workflowContent).toString('base64'),
                    branch: branchName,
                }),
            }
        );

        if (!createFileResponse.ok) {
            const error = await createFileResponse.text();
            throw new Error(`Failed to create workflow file: ${error}`);
        }

        // Create the PR
        const prResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${token}`,
                Accept: 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                title: '🤖 MetaMorph AI: Enable Self-Healing',
                body: `## 🚀 Welcome to MetaMorph AI!

This PR sets up automatic self-healing for your repository.

### What's Included:
- \`.github/workflows/metamorph-ai.yml\` - Automated healing workflow

### How It Works:
1. When issues are detected, the workflow automatically:
   - Analyzes the code
   - Applies fixes using AI
   - Creates a PR with the changes

### Next Steps:
1. **Merge this PR** to enable self-healing
2. **Add Secret:** Go to Settings → Secrets → Actions and add:
   - \`ANTHROPIC_API_KEY\` - Your Anthropic/OpenRouter API key
3. **Trigger from Dashboard:** Use the MetaMorph dashboard to trigger healing

That's it! Your repository is now protected by autonomous AI healing. 🛡️`,
                head: branchName,
                base: defaultBranch,
            }),
        });

        if (!prResponse.ok) {
            const error = await prResponse.text();
            throw new Error(`Failed to create PR: ${error}`);
        }

        const prData = await prResponse.json();

        return NextResponse.json({
            success: true,
            pr_url: prData.html_url,
            pr_number: prData.number,
            message: 'Setup PR created successfully!',
        });

    } catch (error) {
        console.error('Setup workflow error:', error);
        return NextResponse.json(
            {
                success: false,
                error: error instanceof Error ? error.message : 'Failed to set up workflow'
            },
            { status: 500 }
        );
    }
}
